### ISSUE TITLE
mxnet reinstall?

### ISSUE THREAD

**Issue by SerailHydra** [tbd-ai/tbd-tools#1]
According to the README, looks like the user can directly use the modified mxnet after run patch_profiler.sh, but perhaps mxnet needs to be reinstalled first?

Please suggest in README that the modified mxnet is better to be installed under virtual environment if re-installation is necessary.

PS: please enclose the code with
```
<code>...
```
check other README files under tbd-suite for details.
@olympian94

**Comment by olympian94** [comment]
Yes it needs to be re-installed. I updated readme file with more detailed descriptions and code tags.
