### ISSUE TITLE
mxnet reinstallation failed

### ISSUE THREAD

**Issue by SerailHydra** [tbd-ai/tbd-tools#2]
I got this error while doing make -j:

In file included from src/imperative/cached_op.cc:21:0:
src/imperative/./imperative_utils.h:73:1: error: stray ‘`’ in program
 ``  if (ctx.dev_mask() == gpu::kDevMask) {
 ^
src/imperative/./imperative_utils.h:73:1: error: stray ‘`’ in program
Makefile:349: recipe for target 'build/src/imperative/cached_op.o' failed
make: *** [build/src/imperative/cached_op.o] Error 1

**Comment by SerailHydra** [comment]
@olympian94

**Comment by olympian94** [comment]
Fixed. I'm running make clean_all; make; just to double check that no other stray characters have cropped in.

**Comment by olympian94** [comment]
Update: the current patch file compiles properly after make clean_all
