### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by SerailHydra** [tbd-ai/tbd-tools#4]
@olympian94 did you see this?

src/c_api/c_api.cc:47:26: fatal error: cuda_runtime.h: No such file or directory

**Comment by olympian94** [comment]
No I did not  see this error, double check your CUDA path.
```
echo $PATH
which nvcc
```
Double check that nvcc path is the same as the CUDA path in your $PATH variable.

**Comment by SerailHydra** [comment]
I tried a lot of times, the problem is that I have no such issue when installing regular MXNet. This issue always shows up when installing the modified MXNet

**Comment by SerailHydra** [comment]
Please check if any other configurations that are missing in the document

**Comment by olympian94** [comment]
Yes it is a path issue, your CUDA_PATH is not correctly set, I have updated the installation instructions to reflect all the requirements.
