### ISSUE TITLE
mxnet version

### ISSUE THREAD

**Issue by SerailHydra** [tbd-ai/tbd-tools#6]
I just checked the version of the mxnet code base, seems to be 0.12.1 rather than 0.12.0. Is this the same on your machine? @olympian94

**Comment by olympian94** [comment]
Yes it is the same, I have been working with the Sockeye archive branch with Sockeye Version 1.12.3 and it says that it needs MXNet v0.12.1 but I ported the memory profiler to MXNet V0.12.0 and have been using it with no issues.
