### ISSUE TITLE
Specify how to terminate the training process

### ISSUE THREAD

**Issue by SerailHydra** [tbd-ai/tbd-tools#7]
Seems that current document didn't tell users when to kill the training process. Maybe add a few tips for users on how to do it? @olympian94

**Comment by olympian94** [comment]
I didn't think we need to mention that. How long training runs is controlled by max_updates or crudely, it can be done with Ctrl+C.
Maybe you have a point, I willl add some comments about it.

**Comment by SerailHydra** [comment]
1, the `max_updates` variable is there for sockeye only. Users will use the profiler to profile other models and they don't have this.

2, the users need to know that they have to ctrl+c, this is usually not considered as a regular step.

3, the users need to know when it is safe to do ctrl+c so that they can have a good enough result.

Do you think you can quickly come up with some hints on this?

**Comment by olympian94** [comment]
Will do but these things can be figured out with few runs, its no big deal
